{% set name = "xpdtools" %}
{% set version = "0.6.0" %}
{% set sha256 = "cda6cd67b7fa1cf5385d1a9eab45bbb7ff18ba588c8caacc4ad2b1b66579ec95" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://github.com/xpdAcq/{{ name }}/releases/download/{{ version }}/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed . 
  entry_points:
    - image_to_iq = xpdtools.cli.process_tiff:run_main

requirements:
  build:
    - python >=3
    - pip 
  run:
    - python >=3
    - numpy
    - scipy
    - scikit-beam
    - pyyaml
    - pyfai
    - rapidz
    - fire
    - pims
    - fabio
    - numba
    - matplotlib
    - tqdm
    - scikit-learn


test:
  imports:
    - xpdtools
    - xpdtools.tools
    - xpdtools.cli.process_tiff
  commands:
    - image_to_iq -- --help

about:
  home: https://github.com/xpdAcq/xpdtools
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Analysis Tools for XPD'

  doc_url: https://xpdacq.github.io/xpdtools/
  dev_url: https://github.com/xpdAcq/xpdtools

extra:
  recipe-maintainers:
    - CJ-Wright
