travis:
  secure:
    BINSTAR_TOKEN: Sg/xxNGWOXv1/YWuMw/0DqTabLZfWtu79FWeWUalCTY8ZIhVtI/0DXfRO2KziCRl9RaybvSKFyi+TbmCF0EmHSUDReZ9acNc9lhPmmg5LplDzkzxKVRY13XtK2nZoZ6Zrp7LoTe3rV9AZTip46R5V7wdETwuN3lD19AoyZpK24wxe3eMm/EWfInhcsukZJzKLrlEKXYdJp0GFl5YhfRNwKnF+iY2xf5mu6crJJSzBdMwXOu57nEfsDm3n/mFhIBp9gJxfHiJ6w3YHBh/pGfRyesg4m15X2c1Qvb8Vn2xlv6+nhtbrK3Jj2Unvc/+Vdy0jZ7GyiPoUu72C2nbO107ckGc3jcJNxGN/wPPbnMLcMAJ7mnwOmuWmvM/+6OeDQH8OMj7iNoNsv0vhYSfnIKlbfk44S9SnMuMaf6Y4BCUBCJVp8N4lJR3Uqouxx++T/1eQ/7Y3VqYB6J6JkKuETaNcT24xtI/PGJ4KOwda7j+45MiS2e4VTGpcxzY08lHSsQs6315Xge3V69lY/faxj4jBh5NthAkog8SibVloKlMS3o6ec285ae6Cn4kFo3dprsbBPh8RgRcODdq+9pXozUuoKzXW+hq1Ldwatoch//B2jvZH8FBJcFxaTmDQF2QyUlsuGq5YpxrptjE3g9xpzAWyrBuh6N0mSrMARhxSg2m+4M=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
